sprint__4
whoisbulat/qa_python pull request #3
Opened 2023-09-25 23:20 UTC by whoisbulat

2023-09-27 20:11 UTC, kadirovgm requested changes

2023-09-27 20:11 UTC, kadirovgm commented on README.md
> +1  test_add_new_book_add_two_books - проверка добавления двух книг
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов

2023-09-27 20:11 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize("book_name", [
можно лучше: идея абсолютно верная, молодец! Но я думаю что тут можно было бы обойтись и только граничными значениями, 1, 40, ну и 21 да тоже можно - больше данных уже избыточно

2023-09-27 20:11 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize("book_name", [
отлично!

2023-09-27 20:11 UTC, kadirovgm commented on tests.py
> +    def test_get_books_genre_two_valid_name_book_received(self):
нужно исправить: кажется этот тест избыточен, к тому же тут set_genre никакой роли не играет, так как и без жанра книга может быть добавлена в словрь, а возможность добавить в словарь две книги ты уже проверял здесь: test_add_new_book_add_two_books

2023-09-27 20:11 UTC, kadirovgm commented on tests.py
> +        collector.set_book_genre('Планета сокровищ', 'Мультфильмы')
нужно исправить: лучше чтобы в словаре было как минимум две книги, чтобы убедиться что метод возвращает только нужную нам книгу

2023-09-27 20:11 UTC, kadirovgm commented on tests.py
> +        collector.set_book_genre('Тайна Коко', 'Мультфильмы')
нужно исправить: в данном случае set_genres никакой роли не играет, можно убрать

2023-09-27 20:11 UTC, kadirovgm commented on tests.py
> +    def test_get_list_of_favorites_books_one_book_exists_returns_list_with_one_book(self):
нужно исправить: а чем этот тест принципиально отличается от test_add_book_in_favorites_one_book_added ?

2023-09-30 16:39 UTC, whoisbulat commented on README.md
> +1  test_add_new_book_add_two_books - проверка добавления двух книг
Добавил описание проекта и использованные бибилиотеки

2023-09-30 16:42 UTC, whoisbulat commented on tests.py
> +    @pytest.mark.parametrize("book_name", [
В тесте test_add_new_book_valid_number_added оставил проверки граничных значений и внутри 1, 40 и 21. Другие убрал

2023-09-30 16:44 UTC, whoisbulat commented on tests.py
> +    def test_get_books_genre_two_valid_name_book_received(self):
Удалил тест

2023-09-30 16:50 UTC, whoisbulat commented on tests.py
> +        collector.set_book_genre('Тайна Коко', 'Мультфильмы')
В тесте test_delete_book_from_favorites_book_exists_book_removed убрал set_genres

2023-09-30 16:53 UTC, whoisbulat commented on tests.py
> +    def test_get_list_of_favorites_books_one_book_exists_returns_list_with_one_book(self):
Изменил тест. Теперь тест называется test_get_list_of_favorites_books_two_book_exists_returns_list_with_two_book - проверка возвращения 2-ух книг из избранного 
https://github.com/whoisbulat/qa_python/pull/3/commits/989a1db85142cc88e3d5a6bd2bb2c01b06c4ea0e#diff-f455f302936271d755f6892d443786094d2607b505ff180ca817cb9eeabe1e5e

2023-10-01 20:45 UTC, kadirovgm approved these changes

2023-10-01 20:45 UTC, kadirovgm commented on tests.py
> +        ("Д" * 21)
отлично!

2023-10-06 21:03 UTC, merged